name: Content Error Report
description: Report a content-error-related issue
title: "[Content error]: "
labels: ["content error","invalid"]
assignees:
  - andresmup
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a content-related issue!
  - type: textarea
    id: Details
    attributes:
      label: Where and what is the content issue?
      description: Provide details about the content problem you encountered.
    validations:
      required: true
  - type: textarea
    id: CorrectionSuggestion
    attributes:
      label: Suggestion for Improvement
      description: |
        If you have a suggestion for correcting the content, please provide it here. Remember to include a link to documentation justifying the change.
      validations:
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://raw.githubusercontent.com/Andresmup/github-foundations/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
