name: Syntax improvement Report
description: Report a a syntax related issue
title: "[Syntax]: "
labels: ["syntax"]
assignees:
  - andresmpaws
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a syntax-related issue!
  - type: textarea
    id: Details
    attributes:
      label: Where and what is the syntax issue?
      description: Provide details about the syntax problem you encountered.
    validations:
      required: true
  - type: textarea
    id: CorrectionSuggestion
    attributes:
      label: Suggestion for Improvement
      description: |
        If you have a suggestion for improving the syntax, please provide it here.
    validations:
        required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://raw.githubusercontent.com/Andresmup/github-foundations/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true